package A006iterativeStructure;

import java.util.Scanner;

/**
 * @author Uriel Neves Silva (https://gitlab.com/a253119un)
 * This is a code that generates a random number between 1 and the selected number and asks the user to guess it
 * 
 * 
 * STEP BY STEP:
 * 1. Instantiate the scanner
 * 2. Get the maximum number from user input
 * 3. Get the number of attempts from user input
 * 4. Generate the random number
 * 5. Create the main game loop
 * 6. Get the user's guess
 * 7. Compare the user's guess with the generated number
 * 8. Update the number of tries
 * 9. Return the result
 * 10. Go back to step 5 until the user wins or loses
 * 11. Close the scanner
 */

class ItStructure1 {

//================================================================================
// CONSTANTS
//================================================================================
    
    // This is the minimum value for the random number
    private static final byte MINIMUM_NUMBER = 1;

    // These are the minimum and maximum values for the maximum number that can be generated by the program
    private static final byte MINIMUM_OF_MAXIMUM_NUMBER = 10;
    private static final byte MAXIMUM_OF_MAXIMUM_NUMBER = 100;

    // These are the minimum and maximum values for the number of attempts
    private static final byte MINIMUM_OF_TRIES = 2;
    private static final byte MAXIMUM_OF_TRIES = 10;

//================================================================================
// MAIN FUNCTION
//================================================================================


    public static void main(String[] args) {

        Scanner userKeyboardInput = new Scanner(System.in);

        // Initial variables
        byte currentTries = 1; 
        byte guessedNumber = 0;
        byte result = 2; // 0 = won, 1 = too high, 2 = too low

        // Get user input with delimited values maximum number = [10, 100] and maximum tries = [2, 10]
        System.out.println("");
        byte maximumNumber = getByteInputDelimited("Enter the maximum number: (10 .. 100): ", userKeyboardInput, MINIMUM_OF_MAXIMUM_NUMBER, MAXIMUM_OF_MAXIMUM_NUMBER);
        byte maximumTries = getByteInputDelimited("Enter the number of attempts: (2 .. 10): ", userKeyboardInput, MINIMUM_OF_TRIES, MAXIMUM_OF_TRIES);

        // Generate a random number between 1 and the selected number = [1, 100]
        byte generatedNumber = randomNumber(MINIMUM_NUMBER, maximumNumber);


        // Main game loop
        while (result != 0) {

            // Losing condition: maximum number of tries reached
            if (currentTries > maximumTries) {
                System.out.print("You have lost! \nBye!");
                break;
            }

            // Constrained input
            while ( !(MINIMUM_NUMBER <= guessedNumber) || !(guessedNumber <= maximumNumber)) {
                System.out.printf("ATTEMPT %d. Enter %d to %d: ", currentTries, MINIMUM_NUMBER, maximumNumber);
                guessedNumber = userKeyboardInput.nextByte();
            }

            // Increment the number of tries
            currentTries++; 

            // Main game logic/comparisons
            result = guessNumber(guessedNumber, generatedNumber);

            // Reset guessed number, otherwise the game will get stuck in a loop
            guessedNumber = 0;

        } // END OF THE GAME LOOP

        userKeyboardInput.close();

    } // MAIN FUNCTION END

//================================================================================
// FUNCTIONS
//================================================================================

    
    /**
     * This method takes a Scanner object and a String object as parameters
     * and returns a byte object. It prints the String object to the console
     * and then reads a byte from the console and returns it as the result if it is
     * within a given range.
     * 
     * @param stringMessage The String object to be printed to the console.
     * @param scannerName The Scanner object to read from.
     * @param minimumValue The minimum value of the range.
     * @param maximumValue The maximum value of the range.
     * @return The byte object read from the console.
     */
    static byte getByteInputDelimited(String stringMessage,Scanner scannerName, byte minimumValue, byte maximumValue) {
            byte chosenNumber = 0;
            while ( !(minimumValue <= chosenNumber) || !(chosenNumber <= maximumValue)) // Constrained input, while the input is not within the range
            {
                System.out.print(stringMessage); // Keep asking for input
                chosenNumber = scannerName.nextByte();
            }
            return chosenNumber;
    }

    /**
     * This method generates a random number between minNumber and maxNumber.
     * It uses the Math.random() method to generate a double between 0.0 and 1.0,
     * then it multiplies the result by the difference of maxNumber and minNumber plus 1,
     * and finally it adds the minimum number to the result.
     * The result is then cast to a byte.
     * 
     * @param minNumber The minimum value of the range.
     * @param maxNumber The maximum value of the range.
     * @return A random byte number between minNumber and maxNumber.
     */
    static byte randomNumber(byte minNumber, byte maxNumber) {
        return (byte) (Math.random() * (maxNumber - minNumber + 1) + minNumber);
    }

    /**
     * This method takes two byte objects as parameters and compares them.
     * If the guessed number is equal to the generated number, it prints a success message and returns 0.
     * If the guessed number is less than the generated number, it prints a too-low message and returns -1.
     * If the guessed number is greater than the generated number, it prints a too-high message and returns 1.
     * 
     * @param guessedNumber The guessed number.
     * @param generatedNumber The generated number.
     * @return A byte object containing -1 if the guessed number is too low, 0 if it is correct, or 1 if it is too high.
     */
    static byte guessNumber(byte guessedNumber, byte generatedNumber) {
        if (guessedNumber == generatedNumber) {
            System.out.println("YOU HAVE WON!!! THE END.");
            return (byte) 0;
        }
        else if (guessedNumber < generatedNumber) {
            System.out.printf("Too low! ");
            return (byte) -1;
        }
        else {
            System.out.printf("Too high! ");
            return (byte) 1;
        }
    }

} // MAIN CLASS END
// END
