package A010Player.PlayerEnum;

/**
 * PlayerTest.java
 * Test class for Player, this is the main method class
 * TESTS GENERATED BY ARTIFICIAL INTELLIGENCE
 * Tests all constructors, methods, getters and setters
 * @author  Uriel Neves Silva (https://gitlab.com/a253119un)
 */
public class PlayerTest {
    
    public static void main(String[] args) {
        
        //1. Constructor 1
        System.out.println("=== TEST 1: Constructor 1 (all attributes except cards) ===");
        Player player1 = new Player("Lionel", "Messi", 1.70f, 72.0f, (byte)35, Sex.MAN, 150, Team.PSG, Position.FORWARD, true);
        System.out.println(player1.toString());
        System.out.println();
        
        //2. Constructor 2
        System.out.println("=== TEST 2: Constructor 2 (name, surname, height, weight, team, position) ===");
        Player player2 = new Player("Cristiano", "Ronaldo", 1.87f, 83.0f, Team.JUV, Position.FORWARD);
        System.out.println(player2.toString());
        System.out.println();
        
        //3. Constructor 3
        System.out.println("=== TEST 3: Constructor 3 (name, surname, sex, team, position) ===");
        Player player3 = new Player("Alexia", "Putellas", Sex.WOMAN, Team.FCB, Position.MIDFIELDER);
        System.out.println(player3.toString());
        System.out.println();
        
        //4. Constructor 4
        System.out.println("=== TEST 4: Constructor 4 (name, surname, age, sex, team, position) ===");
        Player player4 = new Player("Pedri", "González", (byte)21, Sex.MAN, Team.FCB, Position.MIDFIELDER);
        System.out.println(player4.toString());
        System.out.println();
        
        //5. Test increasePoints with 100 for an active player, it should be TRUE
        System.out.println("=== TEST 5: increasePoints (active player) ===");
        Player player5 = new Player("Test", "Player", Sex.MAN, Team.RM, Position.DEFENDER);
        int pointsBefore5 = player5.getPoints(); 
        boolean result5 = player5.increasePoints(100); // If player is active and red cards < 2
        System.out.println("Result: " + result5 + " (expected: true)");
        System.out.println("Points before: " + pointsBefore5 + ", Points after: " + player5.getPoints());
        System.out.println();
        
        //6. Test increasePoints for an inactive player, it should be FALSE
        System.out.println("=== TEST 6: increasePoints (inactive player) ===");
        Player player6 = new Player("Inactive", "Player", Sex.MAN, Team.SFC, Position.GOALKEEPER);
        player6.setActive(false); // Set player to inactive
        int pointsBefore6 = player6.getPoints();
        boolean result6 = player6.increasePoints(50); // Player is inactive
        System.out.println("Result: " + result6 + " (expected: false)");
        System.out.println("Points before: " + pointsBefore6 + ", Points after: " + player6.getPoints());
        System.out.println();
        
        //7. Test decreasePoints (5 points) for a player with enough points (100)
        System.out.println("=== TEST 7: decreasePoints (5 points from 100) ===");
        Player player7 = new Player("Decrease", "Test", Sex.MAN, Team.BNF, Position.FORWARD);
        int pointsBefore7 = player7.getPoints(); 
        boolean result7 = player7.decreasePoints(5);
        System.out.println("Result: " + result7 + " (expected: true)");
        System.out.println("Points before: " + pointsBefore7 + ", Points after: " + player7.getPoints() + " (expected: 95)");
        System.out.println();
        
        //8. Test decreasePoints (150 points) for a player with (95 points), it should be FALSE
        System.out.println("=== TEST 8: decreasePoints (150 points from 95) ===");
        int pointsBefore8 = player7.getPoints();
        boolean result8 = player7.decreasePoints(150);
        System.out.println("Result: " + result8 + " (expected: true)");
        System.out.println("Points before: " + pointsBefore8 + ", Points after: " + player7.getPoints());
        System.out.println();
        
        //9. Test decreasePoints of a player with negative number (-15), it should be FALSE
        System.out.println("=== TEST 9: decreasePoints (negative number -15) ===");
        Player player9 = new Player("Negative", "Test", Sex.MAN, Team.PSG, Position.MIDFIELDER);
        int pointsBefore9 = player9.getPoints();
        boolean result9 = player9.decreasePoints(-15); // The method decrease points only accepts points > 0
        System.out.println("Result: " + result9 + " (expected: false)");
        System.out.println("Points before: " + pointsBefore9 + ", Points after: " + player9.getPoints());
        System.out.println();
        
        //10. Test decrease points of an inactive player, it should be FALSE
        System.out.println("=== TEST 10: decreasePoints (inactive player) ===");
        Player player10 = new Player("Inactive", "Player2", Sex.MAN, Team.JUV, Position.DEFENDER);
        player10.setActive(false);
        int pointsBefore10 = player10.getPoints();
        boolean result10 = player10.decreasePoints(20);
        System.out.println("Result: " + result10 + " (expected: false)");
        System.out.println("Points before: " + pointsBefore10 + ", Points after: " + player10.getPoints());
        System.out.println();
        
        //11. Test giveCard() to an active player with 0 cards, it should be true
        System.out.println("=== TEST 11: giveCard (0 cards) ===");
        Player player11 = new Player("Card", "Test", Sex.MAN, Team.FCB, Position.FORWARD);
        byte cardsBefore11 = player11.getCards();
        boolean result11 = player11.giveCard();
        System.out.println("Result: " + result11 + " (expected: true)");
        System.out.println("Cards before: " + cardsBefore11 + ", Cards after: " + player11.getCards());
        System.out.println();
        
        //12. Test giveCard() to an active player with 1 cards, it should be true
        System.out.println("=== TEST 12: giveCard (1 card) ===");
        byte cardsBefore12 = player11.getCards();
        boolean result12 = player11.giveCard();
        System.out.println("Result: " + result12 + " (expected: true)");
        System.out.println("Cards before: " + cardsBefore12 + ", Cards after: " + player11.getCards());
        System.out.println();
        
        //13. Test giveCard() to an active player with 5 cards (MAX_CARDS), it should be false
        System.out.println("=== TEST 13: giveCard (at MAX_CARDS) ===");
        player11.giveCard();
        player11.giveCard();
        player11.giveCard();
        byte cardsBefore13 = player11.getCards();
        boolean result13 = player11.giveCard();
        System.out.println("Result: " + result13 + " (expected: false)");
        System.out.println("Cards before: " + cardsBefore13 + ", Cards after: " + player11.getCards());
        System.out.println();
        
        //Getters
        System.out.println("=== TESTING GETTERS ===");
        Player testPlayer = new Player("Gerard", "Piqué", 1.94f, 85.0f, (byte)37, Sex.MAN, 120, Team.FCB, Position.DEFENDER, true);
        testPlayer.giveCard();
        testPlayer.giveCard();
        
        //14. getName
        System.out.println("14. getName: " + testPlayer.getName());
        
        //15. getSurname
        System.out.println("15. getSurname: " + testPlayer.getSurname());
        
        //16. getHeight
        System.out.println("16. getHeight: " + testPlayer.getHeight());
        
        //17. getWeight
        System.out.println("17. getWeight: " + testPlayer.getWeight());
        
        //18. getAge
        System.out.println("18. getAge: " + testPlayer.getAge());
        
        //19. getSex
        System.out.println("19. getSex: " + testPlayer.getSex());
        
        //20. getTeam
        System.out.println("20. getTeam: " + testPlayer.getTeam());
        
        //21. getTeam getName
        System.out.println("21. getTeam().getName(): " + testPlayer.getTeam().getName());
        
        //22. getTeam getCountry
        System.out.println("22. getTeam().getCountry(): " + testPlayer.getTeam().getCountry());
        
        //23. getPosition
        System.out.println("23. getPosition: " + testPlayer.getPosition());
        
        //24. getPoints
        System.out.println("24. getPoints: " + testPlayer.getPoints());
        
        //25. getCards
        System.out.println("25. getCards: " + testPlayer.getCards());
        
        //26. isActive
        System.out.println("26. isActive: " + testPlayer.isActive());
        System.out.println();
        
        //Setters
        System.out.println("=== TESTING SETTERS ===");
        Player setterTest = new Player("Test", "Setter", Sex.MAN, Team.RM, Position.MIDFIELDER);
        
        //27. setName
        System.out.println("27. setName:");
        System.out.println("   Before: " + setterTest.getName());
        setterTest.setName("NewName");
        System.out.println("   After: " + setterTest.getName());
        
        //28. setSurname
        System.out.println("28. setSurname:");
        System.out.println("   Before: " + setterTest.getSurname());
        setterTest.setSurname("NewSurname");
        System.out.println("   After: " + setterTest.getSurname());
        
        //29. setHeight
        System.out.println("29. setHeight:");
        System.out.println("   Before: " + setterTest.getHeight());
        setterTest.setHeight(1.85f);
        System.out.println("   After: " + setterTest.getHeight());
        
        //30. setWeight
        System.out.println("30. setWeight:");
        System.out.println("   Before: " + setterTest.getWeight());
        setterTest.setWeight(78.5f);
        System.out.println("   After: " + setterTest.getWeight());
        
        //31. setAge
        System.out.println("31. setAge:");
        System.out.println("   Before: " + setterTest.getAge());
        setterTest.setAge((byte)25);
        System.out.println("   After: " + setterTest.getAge());
        
        //32. setTeam
        System.out.println("32. setTeam:");
        System.out.println("   Before: " + setterTest.getTeam().getName());
        setterTest.setTeam(Team.PSG);
        System.out.println("   After: " + setterTest.getTeam().getName());
        
        //33. setPosition
        System.out.println("33. setPosition:");
        System.out.println("   Before: " + setterTest.getPosition());
        setterTest.setPosition(Position.GOALKEEPER);
        System.out.println("   After: " + setterTest.getPosition());
        
        //34. setPoints
        System.out.println("34. setPoints:");
        System.out.println("   Before: " + setterTest.getPoints());
        setterTest.setPoints(250);
        System.out.println("   After: " + setterTest.getPoints());
        
        //35. setActive
        System.out.println("35. setActive:");
        System.out.println("   Before: " + setterTest.isActive());
        setterTest.setActive(false);
        System.out.println("   After: " + setterTest.isActive());
        
        System.out.println("\n=== ALL TESTS COMPLETED ===");
    }
}